name: deploment du frontend de social network

on:
  push:
    branches:
      - main:
jobs:
  recupere-projet:
    runs-on: ubuntu-latest

    steps:
    - name: recuperation du code source
      uses: actions/checkout@v3